# ARTHMAETIC OPERATON

In [5]:
import pandas as pd
var =pd. DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [6]:
var["C"]= var["A"]+ var["B"]
var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

# substractor

In [7]:
import pandas as pd
var =pd. DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var["C"]= var["A"]-var["B"]
var

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

# divide

In [8]:
import pandas as pd
var =pd. DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var["C"]= var["A"]/var["B"]
var

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

# multiple

In [9]:
import pandas as pd
var =pd. DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var["C"]= var["A"]*var["B"]
var

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

# moduls

In [10]:
import pandas as pd
var =pd. DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var["C"]= var["A"]%var["B"]
var

   A  B  C
0  1  5  1
1  2  6  2
2  3  7  3
3  4  8  4

# power

In [12]:
import pandas as pd
var =pd. DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var["C"]= var["A"]**var["B"]
var

   A  B      C
0  1  5      1
1  2  6     64
2  3  7   2187
3  4  8  65536

In [15]:
import pandas as pd

# DataFrame banana
var1 = pd.DataFrame({
    "A": [10, 25, 15, 30],
    "B": [5, 6, 7, 8]
})

# Nayi column 'python' add kar rahe hain — jahan A <= 20 hoga
var1["python"] = var1["A"] <= 20
var1["column"] = var1["B"] >= 6

var1

    A  B  python  column
0  10  5    True   False
1  25  6   False    True
2  15  7    True    True
3  30  8   False    True

# ---delete and insert function ----

# insert

In [16]:
import pandas as pd
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var

   A  B      C
0  1  5      1
1  2  6     64
2  3  7   2187
3  4  8  65536

In [17]:
var.insert(2,"python", var["B"])# index python heading  var["B"])copy
var

   A  B  python      C
0  1  5       5      1
1  2  6       6     64
2  3  7       7   2187
3  4  8       8  65536

In [20]:
var.insert(2,"python_1",[11,12,13,14]) #new list create karna --- python heading 11 12 13 14
var

   A  B  python_1  python_  python      C
0  1  5        11       11       5      1
1  2  6        12       12       6     64
2  3  7        13       13       7   2187
3  4  8        14       14       8  65536

In [21]:
# data copy karna ho 
var["python_12"] = var["B"][:3]#yaha mujh jitna chahiye nu scling kar dege 5.0 6.0 7.0 NaN
var

   A  B  python_1  python_  python      C  python_12
0  1  5        11       11       5      1        5.0
1  2  6        12       12       6     64        6.0
2  3  7        13       13       7   2187        7.0
3  4  8        14       14       8  65536        NaN

# Delete

In [27]:
import pandas as pd

# Correct DataFrame
var1 = pd.DataFrame({
    "A": [1,2,3,4],
    "B": [5,6,7,8],
    "C": [11,12,13,14]
})

# Column B ko remove karke naya variable me store karna
var12 = var1.pop("B")#

var12
var1

   A   C
0  1  11
1  2  12
2  3  13
3  4  14

In [28]:
import pandas as pd

# Correct DataFrame
var1 = pd.DataFrame({
    "A": [1,2,3,4],
    "B": [5,6,7,8],
    "C": [11,12,13,14]
})
del var1["A"]# delete form
var1

   B   C
0  5  11
1  6  12
2  7  13
3  8  14

# write csv file in pythom

In [1]:
# Comma-Separated Values. Ye ek simple file format hai jo data ko tabular (table) form me store karta hai, jaise Excel ka spreadsheet,
#lekin ye plain text hota hai.


import pandas as pd
dis = {"A":[1,2,3,4,5,6],"B":[1,2,3,4,5,6],"c":[1,2,3,4,5,6]}
d = pd.DataFrame(dis)
d
d.to_csv("test_new.csv",index= False,header = [1,2,3])# index nhi hoga header bhi change ho jayega

# -----Read csv filesin pandas

In [2]:
import pandas as pd
csv1= pd.read_csv("penguins.csv")
csv1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [5]:
import pandas as pd
csv1= pd.read_csv("penguins.csv",nrows=5)# nrows jo mujhe row chahiye vahi milega
csv1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [6]:
import pandas as pd
csv1= pd.read_csv("penguins.csv",usecols=["species"])# usecols jo chahiye vahi mujhe milega
csv1

    species
0    Adelie
1    Adelie
2    Adelie
3    Adelie
4    Adelie
..      ...
339  Gentoo
340  Gentoo
341  Gentoo
342  Gentoo
343  Gentoo

[344 rows x 1 columns]

In [7]:
import pandas as pd
csv1= pd.read_csv("penguins.csv",usecols=[0,3])# indexing
csv1

    species  bill_depth_mm
0    Adelie           18.7
1    Adelie           17.4
2    Adelie           18.0
3    Adelie            NaN
4    Adelie           19.3
..      ...            ...
339  Gentoo            NaN
340  Gentoo           14.3
341  Gentoo           15.7
342  Gentoo           14.8
343  Gentoo           16.1

[344 rows x 2 columns]

In [9]:
import pandas as pd
csv1= pd.read_csv("penguins.csv",skiprows=[1,3])# colums skip ho jayega
csv1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
1,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
2,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
3,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
4,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
...,...,...,...,...,...,...,...
337,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
338,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
339,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
340,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
341,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [10]:
import pandas as pd
csv1= pd.read_csv("penguins.csv",index_col="species")#ye index ban jayega [species 	]
csv1

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
species,,,,,,
Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...
Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [11]:
import pandas as pd
csv1= pd.read_csv("penguins.csv",header=2)#ye jo heaading bana vah ban jayega	]
csv1

     Adelie  Torgersen  39.5  17.4    186    3800  FEMALE
0    Adelie  Torgersen  40.3  18.0  195.0  3250.0  FEMALE
1    Adelie  Torgersen   NaN   NaN    NaN     NaN     NaN
2    Adelie  Torgersen  36.7  19.3  193.0  3450.0  FEMALE
3    Adelie  Torgersen  39.3  20.6  190.0  3650.0    MALE
4    Adelie  Torgersen  38.9  17.8  181.0  3625.0  FEMALE
..      ...        ...   ...   ...    ...     ...     ...
337  Gentoo     Biscoe   NaN   NaN    NaN     NaN     NaN
338  Gentoo     Biscoe  46.8  14.3  215.0  4850.0  FEMALE
339  Gentoo     Biscoe  50.4  15.7  222.0  5750.0    MALE
340  Gentoo     Biscoe  45.2  14.8  212.0  5200.0  FEMALE
341  Gentoo     Biscoe  49.9  16.1  213.0  5400.0    MALE

[342 rows x 7 columns]

In [13]:
import pandas as pd
csv1= pd.read_csv("penguins.csv",names=["sonu1","sonu2","sonu3","sonu","sonu5","sonu6"])#ye jo first heading ban jaye	]
csv1

,sonu1,sonu2,sonu3,sonu,sonu5,sonu6
species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
Adelie,Torgersen,39.1,18.7,181,3750,MALE
Adelie,Torgersen,39.5,17.4,186,3800,FEMALE
Adelie,Torgersen,40.3,18,195,3250,FEMALE
Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
Gentoo,Biscoe,46.8,14.3,215,4850,FEMALE
Gentoo,Biscoe,50.4,15.7,222,5750,MALE
Gentoo,Biscoe,45.2,14.8,212,5200,FEMALE
Gentoo,Biscoe,49.9,16.1,213,5400,MALE

In [15]:
import pandas as pd
csv1= pd.read_csv("penguins.csv",header=2,dtype={"TOTAL-VALUME":"float"})#ye jo float bana vah ban jayega	]
csv1

     Adelie  Torgersen  39.5  17.4    186    3800  FEMALE
0    Adelie  Torgersen  40.3  18.0  195.0  3250.0  FEMALE
1    Adelie  Torgersen   NaN   NaN    NaN     NaN     NaN
2    Adelie  Torgersen  36.7  19.3  193.0  3450.0  FEMALE
3    Adelie  Torgersen  39.3  20.6  190.0  3650.0    MALE
4    Adelie  Torgersen  38.9  17.8  181.0  3625.0  FEMALE
..      ...        ...   ...   ...    ...     ...     ...
337  Gentoo     Biscoe   NaN   NaN    NaN     NaN     NaN
338  Gentoo     Biscoe  46.8  14.3  215.0  4850.0  FEMALE
339  Gentoo     Biscoe  50.4  15.7  222.0  5750.0    MALE
340  Gentoo     Biscoe  45.2  14.8  212.0  5200.0  FEMALE
341  Gentoo     Biscoe  49.9  16.1  213.0  5400.0    MALE

[342 rows x 7 columns]

# -------- pandas function

In [17]:
import pandas as pd
csv1= pd.read_csv("penguins.csv")
csv1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [18]:
csv1.index

RangeIndex(start=0, stop=344, step=1)

In [19]:
csv1.columns# columns name

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [20]:
csv1.describe()# sab value nikal deta hai

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [22]:
csv1.head()# kuchh data nikal dega

csv1.head(2)# mujhe jo data chahiye vahi milega 2 tk chahiye

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE

In [23]:
csv1.tail()# tk chahiye

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [25]:
csv1[:2]# sclicing kar sakte hai

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE

In [26]:
csv1.index.array# index no

<NumpyExtensionArray>
[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
 ...
 334, 335, 336, 337, 338, 339, 340, 341, 342, 343]
Length: 344, dtype: int64

In [27]:
# convert the numpy array
csv1.to_numpy()

array([['Adelie', 'Torgersen', 39.1, ..., 181.0, 3750.0, 'MALE'],
       ['Adelie', 'Torgersen', 39.5, ..., 186.0, 3800.0, 'FEMALE'],
       ['Adelie', 'Torgersen', 40.3, ..., 195.0, 3250.0, 'FEMALE'],
       ...,
       ['Gentoo', 'Biscoe', 50.4, ..., 222.0, 5750.0, 'MALE'],
       ['Gentoo', 'Biscoe', 45.2, ..., 212.0, 5200.0, 'FEMALE'],
       ['Gentoo', 'Biscoe', 49.9, ..., 213.0, 5400.0, 'MALE']],
      dtype=object)

In [28]:
csv1.sort_index(axis=0,ascending=False)# bade se chhote data aa jata hai

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE

In [32]:
csv1.sort_index(axis=0, ascending=True)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [39]:
import pandas as pd

# Row 0, column 'species' ko update karna
csv1.loc[0, "species"] = "sonukushwaha"# species     
#0    sonukushwaha -- change value

# Updated DataFrame print karna
print(csv1)

          species     island  bill_length_mm  bill_depth_mm  \
0    sonukushwaha  Torgersen            39.1           18.7
1          Adelie  Torgersen            39.5           17.4
2          Adelie  Torgersen            40.3           18.0
3          Adelie  Torgersen             NaN            NaN
4          Adelie  Torgersen            36.7           19.3
..            ...        ...             ...            ...
339        Gentoo     Biscoe             NaN            NaN
340        Gentoo     Biscoe            46.8           14.3
341        Gentoo     Biscoe            50.4           15.7
342        Gentoo     Biscoe            45.2           14.8
343        Gentoo     Biscoe            49.9           16.1

     flipper_length_mm  body_mass_g     sex
0                181.0       3750.0    MALE
1                186.0       3800.0  FEMALE
2                195.0       3250.0  FEMALE
3                  NaN          NaN     NaN
4                193.0       3450.0  FEMALE
..                 ...          ...     ...
339                NaN          NaN     NaN
340              215.0       4850.0  FEMALE
341              222.0       5750.0    MALE
342              212.0       5200.0  FEMALE
343              213.0       5400.0    MALE

[344 rows x 7 columns]

In [40]:
# jo data chahiye
csv1.loc[[2,3],["species","island"]]

  species     island
2  Adelie  Torgersen
3  Adelie  Torgersen

In [45]:
# pura data chahiye to used :
csv1.loc[:, ["species", "island"]]

          species     island
0    sonukushwaha  Torgersen
1          Adelie  Torgersen
2          Adelie  Torgersen
3          Adelie  Torgersen
4          Adelie  Torgersen
..            ...        ...
339        Gentoo     Biscoe
340        Gentoo     Biscoe
341        Gentoo     Biscoe
342        Gentoo     Biscoe
343        Gentoo     Biscoe

[344 rows x 2 columns]

In [49]:
csv1.drop("species",axis=1)

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...
339,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Biscoe,49.9,16.1,213.0,5400.0,MALE

# -------- Handing missing value (draop and fillan)===

In [80]:
import pandas as pd 
csv1 = pd.read_csv("penguins.csv")
csv1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [81]:
csv1.dropna(axis=1)# Nan value remove ho gaya--- axis karne jaha non colum me thi hath gaya

    species     island
0    Adelie  Torgersen
1    Adelie  Torgersen
2    Adelie  Torgersen
3    Adelie  Torgersen
4    Adelie  Torgersen
..      ...        ...
339  Gentoo     Biscoe
340  Gentoo     Biscoe
341  Gentoo     Biscoe
342  Gentoo     Biscoe
343  Gentoo     Biscoe

[344 rows x 2 columns]

In [82]:
csv1.dropna(axis=0)#row

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [83]:
csv1.dropna(how="any")
# any() ka matlab hai: "kya koi bhi value True/1/Non-zero hai?"

# Agar koi bhi value True hai → any() return karega True

# Agar sab False/0 hai → any() return karega False

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [84]:
csv1.dropna(how="all")
# all() check karta hai: "kya sab values True/1/Non-zero hai?"

# Agar sab True hai → return karega True

# Agar koi bhi False/0 hai → return karega False

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [85]:
# subset → sirf selected columns par operation apply karo, puri DataFrame nahi.

# subset →     null value remove

var.dropna(subset=["sex"])#null value remove columns throw

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [86]:
csv1.dropna(inplace=True)#null value remove

csv1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [87]:
csv1.dropna(thresh=3)# ek hi value non value ho

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

# fillna

In [94]:
#csv1= pd.read_csv("penguins.csv")
csv1.fillna("sonu")# jaha NaN hoga vaha sonu ho jayega

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,sonu,sonu,sonu,sonu,sonu
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,sonu,sonu,sonu,sonu,sonu
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [95]:
csv1.fillna({"bill_length_mm":"A","bill_depth_mm":"B","flipper_length_mm":"C"}) yaha value ki jagah apne hisab se fill kar sakte hai ABC

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,A,B,C,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,A,B,C,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [101]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Sonu', None, 'Amit'],
    'Age': [21, 22, None]
})

# Backward fill
df_filled = df.fillna(method="bfill")

print(df_filled)
# fill ki mtlb pichhe ka value dusre me aake fill ho jata hai

   Name   Age
0  Sonu  21.0
1  Amit  22.0
2  Amit   NaN

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20492\37085615.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filled = df.fillna(method="bfill")

In [100]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Sonu', None, 'Amit'],
    'Age': [21, 22, None]
})

# Backward fill
df_filled = df.fillna(method="bfill")

print(df_filled)

   Name   Age
0  Sonu  21.0
1  Amit  22.0
2  Amit   NaN

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20492\1839722920.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filled = df.fillna(method="bfill")

In [103]:
csv1.fillna(12,inplace=True)
csv1

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,12.0,12.0,12.0,12.0,12
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,12.0,12.0,12.0,12.0,12
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [2]:

csv1.fillna("python",limit=2)# har row me python fill ho jitna fill kare to 1ya 2 3ase hi

NameError: name 'csv1' is not defined

# Handing missing value (replace and interpolate) in python

# Replace

In [16]:
import pandas as pd
csv1 = pd.read_csv("penguins.csv")
csv1.replace(to_replace="Adelie", value="golu") #to_replace kya fill karna hai  value jo change karna ho

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,golu,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,golu,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,golu,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,golu,Torgersen,NaN,NaN,NaN,NaN,NaN
4,golu,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [18]:
var.replace([39.1,40.3,36.7],"A")#jo number change karna hoga vah kar lege

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,A,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,A,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,A,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [19]:
var.replace("[A-Za-z]","sonu",regex=True)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,sonusonusonusonusonusonu,sonusonusonusonusonusonusonusonusonu,39.1,18.7,181.0,3750.0,sonusonusonusonu
1,sonusonusonusonusonusonu,sonusonusonusonusonusonusonusonusonu,39.5,17.4,186.0,3800.0,sonusonusonusonusonusonu
2,sonusonusonusonusonusonu,sonusonusonusonusonusonusonusonusonu,40.3,18.0,195.0,3250.0,sonusonusonusonusonusonu
3,sonusonusonusonusonusonu,sonusonusonusonusonusonusonusonusonu,NaN,NaN,NaN,NaN,NaN
4,sonusonusonusonusonusonu,sonusonusonusonusonusonusonusonusonu,36.7,19.3,193.0,3450.0,sonusonusonusonusonusonu
...,...,...,...,...,...,...,...
339,sonusonusonusonusonusonu,sonusonusonusonusonusonu,NaN,NaN,NaN,NaN,NaN
340,sonusonusonusonusonusonu,sonusonusonusonusonusonu,46.8,14.3,215.0,4850.0,sonusonusonusonusonusonu
341,sonusonusonusonusonusonu,sonusonusonusonusonusonu,50.4,15.7,222.0,5750.0,sonusonusonusonu
342,sonusonusonusonusonusonu,sonusonusonusonusonusonu,45.2,14.8,212.0,5200.0,sonusonusonusonusonusonu
343,sonusonusonusonusonusonu,sonusonusonusonusonusonu,49.9,16.1,213.0,5400.0,sonusonusonusonu

In [24]:
var.replace({"species":"[A-Z]"},"sonu", regex=True)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,sonusonusonusonusonusonu,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,sonusonusonusonusonusonu,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,sonusonusonusonusonusonu,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,sonusonusonusonusonusonu,Torgersen,NaN,NaN,NaN,NaN,NaN
4,sonusonusonusonusonusonu,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,sonusonusonusonusonusonu,Biscoe,NaN,NaN,NaN,NaN,NaN
340,sonusonusonusonusonusonu,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,sonusonusonusonusonusonu,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,sonusonusonusonusonusonu,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,sonusonusonusonusonusonu,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [33]:
var.replace(3250.0,method="ffill")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1724\3683544387.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(3250.0,method="ffill")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3800.0,FEMALE
3,Adelie,Torgersen,40.3,18.0,195.0,3800.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [34]:
var.replace("Torgersen",method="bfill")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1724\1507023305.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace("Torgersen",method="bfill")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Biscoe,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Biscoe,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Biscoe,40.3,18.0,195.0,3800.0,FEMALE
3,Adelie,Biscoe,40.3,18.0,195.0,3800.0,FEMALE
4,Adelie,Biscoe,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [36]:
csv1.replace(3250.0,method="ffill",limit=3)# limit dene jitna chahiye utna kar sakte hai

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1724\3637915052.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv1.replace(3250.0,method="ffill",limit=3)# limit dene jitna chahiye utna kar sakte hai

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3800.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

# interpolate

In [46]:
import pandas as pd
var = pd.read_csv("C:\\Users\\LENOVO\Downloads\\car_crashes.csv.")
var

<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1724\3480562868.py:2: SyntaxWarning: invalid escape sequence '\D'
  var = pd.read_csv("C:\\Users\\LENOVO\Downloads\\car_crashes.csv.")

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,NaN,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,NaN,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,NaN,3.360,10.920,10.680,878.41,165.63,CA
5,13.6,NaN,3.808,10.744,12.920,835.50,139.91,CO
6,10.8,NaN,3.888,9.396,8.856,1068.73,167.02,CT
7,16.2,6.156,4.860,14.094,16.038,1137.87,151.48,DE
8,5.9,2.006,1.593,5.900,5.900,1273.89,136.05,DC
9,17.9,3.759,5.191,16.468,16.826,1160.13,144.18,FL
10,15.6,2.964,3.900,14.820,14.508,913.15,142.80,GA
11,17.5,9.450,7.175,14.350,15.225,861.18,120.92,HI
12,15.3,5.508,4.437,13.005,14.994,641.96,82.75,ID
13,12.8,4.608,4.352,12.032,12.288,803.11,139.15,IL
14,14.5,3.625,4.205,13.775,13.775,710.46,108.92,IN
15,15.7,2.669,3.925,15.229,13.659,649.06,114.47,IA
16,17.8,4.806,4.272,13.706,15.130,780.45,133.80,KS
17,21.4,4.066,4.922,16.692,16.264,872.51,137.13,KY
18,20.5,7.175,6.765,14.965,20.090,1281.55,194.78,LA
19,15.1,5.738,4.530,13.137,12.684,661.88,96.57,ME
20,12.5,4.250,4.000,8.875,12.375,1048.78,192.70,MD
21,8.2,1.886,2.870,7.134,6.560,1011.14,135.63,MA
22,14.1,3.384,3.948,13.395,10.857,1110.61,152.26,MI
23,9.6,2.208,2.784,8.448,8.448,777.18,133.35,MN
24,17.6,2.640,5.456,1.760,17.600,896.07,155.77,MS
25,16.1,6.923,5.474,14.812,13.524,790.32,144.45,MO
26,21.4,8.346,9.416,17.976,18.190,816.21,85.15,MT
27,14.9,1.937,5.215,13.857,13.410,732.28,114.82,NE
28,14.7,5.439,4.704,13.965,14.553,1029.87,138.71,NV
29,11.6,4.060,3.480,10.092,9.628,746.54,120.21,NH
30,11.2,1.792,3.136,9.632,8.736,1301.52,159.85,NJ
31,18.4,3.496,4.968,12.328,18.032,869.85,120.75,NM
32,12.3,3.936,3.567,10.824,9.840,1234.31,150.01,NY
33,16.8,6.552,5.208,15.792,13.608,708.24,127.82,NC
34,23.9,5.497,10.038,23.661,20.554,688.75,109.72,ND
35,14.1,3.948,4.794,13.959,11.562,697.73,133.52,OH
36,19.9,6.368,5.771,18.308,18.706,881.51,178.86,OK
37,12.8,4.224,3.328,8.576,11.520,804.71,104.61,OR
38,18.2,9.100,5.642,17.472,16.016,905.99,153.86,PA
39,11.1,3.774,4.218,10.212,8.769,1148.99,148.58,RI
40,23.9,9.082,9.799,22.944,19.359,858.97,116.29,SC
41,19.4,6.014,6.402,19.012,16.684,669.31,96.87,SD
42,19.5,4.095,5.655,15.990,15.795,767.91,155.57,TN
43,19.4,7.760,7.372,17.654,16.878,1004.75,156.83,TX
44,11.3,4.859,1.808,9.944,10.848,809.38,109.48,UT
45,13.6,4.080,4.080,13.056,12.920,716.20,109.61,VT
46,12.7,2.413,3.429,11.049,11.176,768.95,153.72,VA
47,10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA
48,23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV
49,13.8,4.968,4.554,5.382,11.592,670.31,106.62,WI
50,17.4,7.308,5.568,14.094,15.660,791.14,122.04,WY

In [47]:
var.interpolate() # data missing aa jata hai

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1724\3058937733.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  var.interpolate() # data missing aa jata hai

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332000,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421000,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,7.210167,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,6.999333,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,6.788500,3.360,10.920,10.680,878.41,165.63,CA
5,13.6,6.577667,3.808,10.744,12.920,835.50,139.91,CO
6,10.8,6.366833,3.888,9.396,8.856,1068.73,167.02,CT
7,16.2,6.156000,4.860,14.094,16.038,1137.87,151.48,DE
8,5.9,2.006000,1.593,5.900,5.900,1273.89,136.05,DC
9,17.9,3.759000,5.191,16.468,16.826,1160.13,144.18,FL
10,15.6,2.964000,3.900,14.820,14.508,913.15,142.80,GA
11,17.5,9.450000,7.175,14.350,15.225,861.18,120.92,HI
12,15.3,5.508000,4.437,13.005,14.994,641.96,82.75,ID
13,12.8,4.608000,4.352,12.032,12.288,803.11,139.15,IL
14,14.5,3.625000,4.205,13.775,13.775,710.46,108.92,IN
15,15.7,2.669000,3.925,15.229,13.659,649.06,114.47,IA
16,17.8,4.806000,4.272,13.706,15.130,780.45,133.80,KS
17,21.4,4.066000,4.922,16.692,16.264,872.51,137.13,KY
18,20.5,7.175000,6.765,14.965,20.090,1281.55,194.78,LA
19,15.1,5.738000,4.530,13.137,12.684,661.88,96.57,ME
20,12.5,4.250000,4.000,8.875,12.375,1048.78,192.70,MD
21,8.2,1.886000,2.870,7.134,6.560,1011.14,135.63,MA
22,14.1,3.384000,3.948,13.395,10.857,1110.61,152.26,MI
23,9.6,2.208000,2.784,8.448,8.448,777.18,133.35,MN
24,17.6,2.640000,5.456,1.760,17.600,896.07,155.77,MS
25,16.1,6.923000,5.474,14.812,13.524,790.32,144.45,MO
26,21.4,8.346000,9.416,17.976,18.190,816.21,85.15,MT
27,14.9,1.937000,5.215,13.857,13.410,732.28,114.82,NE
28,14.7,5.439000,4.704,13.965,14.553,1029.87,138.71,NV
29,11.6,4.060000,3.480,10.092,9.628,746.54,120.21,NH
30,11.2,1.792000,3.136,9.632,8.736,1301.52,159.85,NJ
31,18.4,3.496000,4.968,12.328,18.032,869.85,120.75,NM
32,12.3,3.936000,3.567,10.824,9.840,1234.31,150.01,NY
33,16.8,6.552000,5.208,15.792,13.608,708.24,127.82,NC
34,23.9,5.497000,10.038,23.661,20.554,688.75,109.72,ND
35,14.1,3.948000,4.794,13.959,11.562,697.73,133.52,OH
36,19.9,6.368000,5.771,18.308,18.706,881.51,178.86,OK
37,12.8,4.224000,3.328,8.576,11.520,804.71,104.61,OR
38,18.2,9.100000,5.642,17.472,16.016,905.99,153.86,PA
39,11.1,3.774000,4.218,10.212,8.769,1148.99,148.58,RI
40,23.9,9.082000,9.799,22.944,19.359,858.97,116.29,SC
41,19.4,6.014000,6.402,19.012,16.684,669.31,96.87,SD
42,19.5,4.095000,5.655,15.990,15.795,767.91,155.57,TN
43,19.4,7.760000,7.372,17.654,16.878,1004.75,156.83,TX
44,11.3,4.859000,1.808,9.944,10.848,809.38,109.48,UT
45,13.6,4.080000,4.080,13.056,12.920,716.20,109.61,VT
46,12.7,2.413000,3.429,11.049,11.176,768.95,153.72,VA
47,10.6,4.452000,3.498,8.692,9.116,890.03,111.62,WA
48,23.8,8.092000,6.664,23.086,20.706,992.61,152.56,WV
49,13.8,4.968000,4.554,5.382,11.592,670.31,106.62,WI
50,17.4,7.308000,5.568,14.094,15.660,791.14,122.04,WY

# merging and concat

# merging

In [5]:
import pandas as pd 
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2=pd.DataFrame({"A":[1,2,3,4],"c":[19,15,10,19]})
pd.merge(var1,var2,on="A")# on-- jo same data hai ek baar likha jaye

   A   B   c
0  1  11  19
1  2  12  15
2  3  13  10
3  4  14  19

In [6]:
import pandas as pd 
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2=pd.DataFrame({"A":[1,2,3,5],"c":[19,15,10,19]})# mai yaha 5 likh diya hu jaha tk same rahega vahi tk nikalega
pd.merge(var1,var2,on="A")# on-- jo same data hai ek baar likha jaye

   A   B   c
0  1  11  19
1  2  12  15
2  3  13  10

In [8]:
import pandas as pd 
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2=pd.DataFrame({"A":[1,2,3,5],"c":[19,15,10,19]})
pd.merge(var1,var2,how="left")# on-- jo same data hai ek baar likha jaye

# left ka data vah data hai jo missing value ko nan karta

   A   B     c
0  1  11  19.0
1  2  12  15.0
2  3  13  10.0
3  4  14   NaN

In [9]:
import pandas as pd 
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2=pd.DataFrame({"A":[1,2,3,5],"c":[19,15,10,19]})
pd.merge(var1,var2,how="right")# on-- jo same data hai ek baar likha jaye

# right ka data vah data hai jo missing value ko nan karta

   A     B   c
0  1  11.0  19
1  2  12.0  15
2  3  13.0  10
3  5   NaN  19

In [10]:
import pandas as pd 
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2=pd.DataFrame({"A":[1,2,3,5],"c":[19,15,10,19]})
pd.merge(var1,var2,how="outer")# on-- jo same data hai ek baar likha jaye

# outer data dono defalt value dega

   A     B     c
0  1  11.0  19.0
1  2  12.0  15.0
2  3  13.0  10.0
3  4  14.0   NaN
4  5   NaN  19.0

In [12]:
#indicator ye bata hai ki konsa data merge konsa nhi

import pandas as pd 
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2=pd.DataFrame({"A":[1,2,3,5],"c":[19,15,10,19]})
pd.merge(var1,var2,how="outer",indicator=True)

   A     B     c      _merge
0  1  11.0  19.0        both
1  2  12.0  15.0        both
2  3  13.0  10.0        both
3  4  14.0   NaN   left_only
4  5   NaN  19.0  right_only

In [20]:
import pandas as pd 
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2=pd.DataFrame({"A":[1,2,3,5],"c":[19,15,10,19]})
pd.merge(var1,var2)

   A   B   c
0  1  11  19
1  2  12  15
2  3  13  10

In [18]:
# yaha data nhi dikh raha hai
#dekhne ke liye left_index=True and right_index=False

#suffixes -- name change karta hai

import pandas as pd 
var1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2=pd.DataFrame({"A":[1,2,3,4],"B":[19,15,10,19]})
pd.merge(var1,var2, left_index=True,right_index=True,suffixes=("name","python"))#suffixes -- name change karta hai

   Aname  Bname  Apython  Bpython
0      1     11        1       19
1      2     12        2       15
2      3     13        3       10
3      4     14        4       19

# concat

In [26]:
import pandas as pd

sr1 = pd.Series([1, 2, 3, 4])
sr2 = pd.Series([11, 21, 31, 41])

result = pd.concat([sr1, sr2])
print(result)

0     1
1     2
2     3
3     4
0    11
1    21
2    31
3    41
dtype: int64

In [34]:
import pandas as pd 
d1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2=pd.DataFrame({"A":[1,2,3,4],"B":[19,15,10,19]})
pd.concat([d1,d2],axis=1)#column
#print(new)

   A   B  A   B
0  1  11  1  19
1  2  12  2  15
2  3  13  3  10
3  4  14  4  19

In [35]:
import pandas as pd 
d1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2=pd.DataFrame({"A":[1,2,3,4],"B":[19,15,10,19]})
pd.concat([d1,d2],axis=0)#row

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
0  1  19
1  2  15
2  3  10
3  4  19

In [38]:
import pandas as pd 
d1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2=pd.DataFrame({"A":[1,2],"B":[19,15]})
pd.concat([d1,d2],join="outer",axis=1)#

   A   B    A     B
0  1  11  1.0  19.0
1  2  12  2.0  15.0
2  3  13  NaN   NaN
3  4  14  NaN   NaN

In [39]:
import pandas as pd 
d1=pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2=pd.DataFrame({"A":[1,2],"B":[19,15]})
pd.concat([d1,d2],join="inner",axis=1)# not missing data

   A   B  A   B
0  1  11  1  19
1  2  12  2  15

In [42]:
import pandas as pd

d1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": [11, 12, 13, 14]})
d2 = pd.DataFrame({"A": [1, 2, 3, 4], "B": [19, 15, 10, 19]})

pd.concat([d1, d2], axis=1, keys=["d1", "d2"])
#print(result)

  d1     d2
   A   B  A   B
0  1  11  1  19
1  2  12  2  15
2  3  13  3  10
3  4  14  4  19

In [43]:
import pandas as pd

d1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": [11, 12, 13, 14]})
d2 = pd.DataFrame({"A": [1, 2, 3, 4], "B": [19, 15, 10, 19]})

pd.concat([d1, d2], axis=0, keys=["d1", "d2"])

      A   B
d1 0  1  11
   1  2  12
   2  3  13
   3  4  14
d2 0  1  19
   1  2  15
   2  3  10
   3  4  19

# ----------- join and append

# join

In [48]:
d1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": [11, 12, 13, 14]} ,index =["a","b","c","d"])
d2 = pd.DataFrame({"C": [1, 2, 3, 4], "D": [19, 15, 10, 19]},index =["a","b","c","d"])

d1.join(d2,how = "outer",lsuffix="sonu")
# right left inner,,lsuffix' 
# lsuffix' ---- heading banta hai
#,,rsuffix' ---right heading dege
0

   A   B  C   D
a  1  11  1  19
b  2  12  2  15
c  3  13  3  10
d  4  14  4  19

# APPEND

In [54]:
import pandas as pd

d1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": [11, 12, 13, 14]}, index=["a", "b", "c", "d"])
d2 = pd.DataFrame({"C": [1, 2, 3, 4], "D": [19, 15, 10, 19]}, index=["a", "b", "c", "d"])

result = pd.concat([d1, d2], axis=0,)
print(result)

     A     B    C     D
a  1.0  11.0  NaN   NaN
b  2.0  12.0  NaN   NaN
c  3.0  13.0  NaN   NaN
d  4.0  14.0  NaN   NaN
a  NaN   NaN  1.0  19.0
b  NaN   NaN  2.0  15.0
c  NaN   NaN  3.0  10.0
d  NaN   NaN  4.0  19.0

In [56]:
import pandas as pd

d1 = pd.DataFrame({"A": [1, 2, 3, 4], "B": [11, 12, 13, 14]}, index=["a", "b", "c", "d"])
d2 = pd.DataFrame({"C": [1, 2, 3, 4], "D": [19, 15, 10, 19]}, index=["a", "b", "c", "d"])

result = pd.concat([d1, d2], axis=0,ignore_index=True)
print(result)

     A     B    C     D
0  1.0  11.0  NaN   NaN
1  2.0  12.0  NaN   NaN
2  3.0  13.0  NaN   NaN
3  4.0  14.0  NaN   NaN
4  NaN   NaN  1.0  19.0
5  NaN   NaN  2.0  15.0
6  NaN   NaN  3.0  10.0
7  NaN   NaN  4.0  19.0

# Group by function

# groupby

In [63]:
import pandas as pd

data =pd.DataFrame({
    "City": ["Lucknow", "Lucknow", "Kanpur", "Kanpur", "Delhi"],
    "Sales": [200, 250, 300, 150, 400]
})

df = pd.DataFrame(data)

print("Original Data:")
print(df)

# Group by City and find total sales
result = df.groupby("City")["Sales"].sum()

print("\nTotal Sales in each City:")
print(result)

Original Data:
      City  Sales
0  Lucknow    200
1  Lucknow    250
2   Kanpur    300
3   Kanpur    150
4    Delhi    400

Total Sales in each City:
City
Delhi      400
Kanpur     450
Lucknow    450
Name: Sales, dtype: int64

In [58]:
result.min()

400

In [59]:
result.max()

450

In [60]:
li=list(result)
li

[400, 450, 450]

# ------- pivot table and melt function

# melt function

In [69]:
import pandas as pd

new =pd.DataFrame({
    "Name": ["Sonu", "Riya", "Aman"],
    "Math": [80, 75, 90],
    "Science": [85, 70, 95]
})
new

   Name  Math  Science
0  Sonu    80       85
1  Riya    75       70
2  Aman    90       95

In [82]:
pd.melt(new, id_vars=["Name"],var_name="python",value_name="adddress")

   Name   python  adddress
0  Sonu     Math        80
1  Riya     Math        75
2  Aman     Math        90
3  Sonu  Science        85
4  Riya  Science        70
5  Aman  Science        95

In [74]:
pd.melt(new, id_vars=["Math"])

   Math variable value
0    80     Name  Sonu
1    75     Name  Riya
2    90     Name  Aman
3    80  Science    85
4    75  Science    70
5    90  Science    95

In [75]:
pd.melt(new, id_vars=["Science"])

   Science variable value
0       85     Name  Sonu
1       70     Name  Riya
2       95     Name  Aman
3       85     Math    80
4       70     Math    75
5       95     Math    90

# pivot

In [83]:
# pivot jo value chahiye vahi milega
import pandas as pd

data = {
    "Name": ["Sonu", "Sonu", "Riya", "Riya"],
    "Subject": ["Math", "Science", "Math", "Science"],
    "Marks": [85, 90, 80, 95]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Using pivot
pivot_df = df.pivot(index="Name", columns="Subject", values="Marks")

print("\nAfter Pivot:")
print(pivot_df)

Original DataFrame:
   Name  Subject  Marks
0  Sonu     Math     85
1  Sonu  Science     90
2  Riya     Math     80
3  Riya  Science     95

After Pivot:
Subject  Math  Science
Name
Riya       80       95
Sonu       85       90

# melt()

In [1]:
# heading change
import pandas as pd

df = pd.DataFrame({
    'Name': ['Sonu', 'Ravi'],
    'Math': [90, 80],
    'Science': [85, 75]
})

print("Original DataFrame:")
print(df)

# Melt the DataFrame
df_melted = pd.melt(df, id_vars=['Name'], var_name='Subject', value_name='Score')

print("\nMelted DataFrame:")
print(df_melted)

Original DataFrame:
   Name  Math  Science
0  Sonu    90       85
1  Ravi    80       75

Melted DataFrame:
   Name  Subject  Score
0  Sonu     Math     90
1  Ravi     Math     80
2  Sonu  Science     85
3  Ravi  Science     75

In [3]:
import pandas as pd

df = pd.DataFrame({"day":[1,2,3,4,5,6],"eng":[10,11,12,13,14,15],"math":[16,17,18,19,20,21]})
df

   day  eng  math
0    1   10    16
1    2   11    17
2    3   12    18
3    4   13    19
4    5   14    20
5    6   15    21

In [8]:
pd.melt(df,id_vars=["eng"])# specific ko id bana sakte hai

    eng variable  value
0    10      day      1
1    11      day      2
2    12      day      3
3    13      day      4
4    14      day      5
5    15      day      6
6    10     math     16
7    11     math     17
8    12     math     18
9    13     math     19
10   14     math     20
11   15     math     21

In [10]:
pd.melt(df,id_vars=["eng"],var_name="python",value_name="wcube")# specific ko id bana sakte hai

    eng python  wcube
0    10    day      1
1    11    day      2
2    12    day      3
3    13    day      4
4    14    day      5
5    15    day      6
6    10   math     16
7    11   math     17
8    12   math     18
9    13   math     19
10   14   math     20
11   15   math     21

# pivot()

In [14]:
import pandas as pd

df = pd.DataFrame({
    'day': ['Mon', 'Tue', 'Mon', 'Tue'],
    'eng': ['A', 'A', 'B', 'B'],
    'score': [90, 95, 85, 80]
})

pivoted = df.pivot(index='day', columns='eng', values='score')
print(pivoted)

eng   A   B
day
Mon  90  85
Tue  95  80

In [15]:
import pandas as pd

df = pd.DataFrame({
    'day': ['Mon', 'Tue', 'Mon', 'Tue'],
    'eng': ['A', 'A', 'B', 'B'],
    'score': [90, 95, 85, 80]
})

pivoted = df.pivot(index='day', columns='eng')
print(pivoted)

    score
eng     A   B
day
Mon    90  85
Tue    95  80

In [16]:
import pandas as pd

df = pd.DataFrame({
    'day': ['Mon', 'Tue', 'Mon', 'Tue', 'Mon'],
    'eng': ['A', 'A', 'B', 'B', 'A'],
    'score': [90, 95, 85, 80, 88]
})

pivoted = df.pivot_table(index='day', columns='eng', values='score', aggfunc='mean', fill_value=0)
print(pivoted)

eng     A     B
day
Mon  89.0  85.0
Tue  95.0  80.0

In [24]:
import pandas as pd

df = pd.DataFrame({
    'day': ['Mon', 'Tue', 'Mon', 'Tue', 'Mon'],
    'eng': ['A', 'A', 'B', 'B', 'A'],
    'score': [90, 95, 85, 80, 88]
})

pivoted = df.pivot_table(
    index='day',
    columns='eng',
    values='score',
    aggfunc='sum',
    margins=True 
)

print(pivoted)

eng    A    B  All
day
Mon  178   85  263
Tue   95   80  175
All  273  165  438